CREATE TABLE PaginaRoles (
    Id INT IDENTITY PRIMARY KEY,
    RutaId INT NOT NULL,
    RolId INT NOT NULL,
    FOREIGN KEY (RolId) REFERENCES Roles(Id),
    FOREIGN KEY (RutaId) REFERENCES Paginas(Id)
);