CREATE PROCEDURE [dbo].[InfoCredito_CrearNucleo]
    @ID_RELACION INT,
    @ID_NUCLEO INT OUTPUT
AS
BEGIN
    SET ANSI_NULLS ON;
    SET QUOTED_IDENTIFIER ON;
    SET NOCOUNT ON;

    INSERT INTO [dbo].[InfoCredito_Nucleos] ([ID_RELACION])
    VALUES (@ID_RELACION);
    SET @ID_NUCLEO = SCOPE_IDENTITY();
END;
GO