--CREATE PROCEDURE [dbo].[InfoCredito_GetNucleo]
--    @ID_NUCLEO INT = NULL,
--    @DOCUMENTO INT = NULL
--AS
--BEGIN
--    --SELECT n.ID_NUCLEO, n.DOCUMENTO, r.*, p.*
--    --FROM [dbo].[InfoCredito_Nucleos] n
--    --INNER JOIN [dbo].[InfoCredito_Personas] p ON n.DOCUMENTO = p.DOCUMENTO
--    --INNER JOIN [dbo].[Relacion] r ON r.IdRelacion = n.ID_RELACION
--    --WHERE
--    --    (@ID_NUCLEO IS NULL OR n.ID_NUCLEO = @ID_NUCLEO)
--    --    AND (
--    --        @DOCUMENTO IS NULL
--    --        OR n.ID_NUCLEO IN (
--    --            SELECT ID_NUCLEO
--    --            FROM [dbo].[InfoCredito_Nucleos]
--    --            WHERE DOCUMENTO = @DOCUMENTO
--    --            AND p.ACTIVO = 1
--    --        )
--    --    )
--END
--GO