CREATE TABLE [dbo].[Creditos]
(
	[ID_CREDITO] INT NOT NULL PRIMARY KEY, 
    [ID_NUCLEO] INT NOT NULL, 
    [ACTIVO] BIT NOT NULL, 
    [MONTO_INICIAL] BIGINT NULL, 
    [FECHA_ENTREGA] DATE NOT NULL, 
    CONSTRAINT [FK_Creditos_ToNucleo] FOREIGN KEY ([ID_NUCLEO]) REFERENCES [Nucleos]([ID_NUCLEO])
)
