CREATE TABLE [dbo].[Direcciones]
(
	[ID_DIRECCION] INT NOT NULL PRIMARY KEY, 
    [ID_PAIS] INT NOT NULL, 
    [ID_DEPARTAMENTO] INT NOT NULL, 
    [ID_LOCALIDAD] INT NOT NULL, 
    [CALLE] NVARCHAR(MAX) NULL, 
    [NUMERO] INT NOT NULL, 
    [MANZANA] INT NOT NULL, 
    [SOLAR] INT NOT NULL, 
    CONSTRAINT [FK_Direcciones_Pais] FOREIGN KEY ([ID_PAIS]) REFERENCES [Paises]([ID]),
    CONSTRAINT [FK_Direcciones_Departamento] FOREIGN KEY ([ID_DEPARTAMENTO]) REFERENCES [Departamentos]([ID]),
    CONSTRAINT [FK_Direcciones_Localidad] FOREIGN KEY ([ID_LOCALIDAD]) REFERENCES [Localidades]([ID])
)
