CREATE TABLE [dbo].[InfoCredito_Direcciones]
(
	[ID_DIRECCION] INT NOT NULL PRIMARY KEY IDENTITY (1, 1), 
    [ID_LOCALIDAD] INT NOT NULL, 
    [CALLE] NVARCHAR(MAX) NULL, 
    [NUMERO] INT NOT NULL, 
    [MANZANA] INT NOT NULL, 
    [SOLAR] INT NOT NULL,
    [OBSERVACIONES] NVARCHAR(MAX) NULL, 
    CONSTRAINT [FK_Direcciones_Localidad] FOREIGN KEY ([ID_LOCALIDAD]) REFERENCES [Localidades]([IdLocalidad])
)
