CREATE TABLE [dbo].[InfoCredito_Creditos]
(
	[ID_CREDITO] INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
    [ID_NUCLEO] INT NOT NULL, 
    [ACTIVO] BIT NOT NULL DEFAULT 1, 
    [MONTO] INT NULL, 
    [FECHA_ENTREGA] DATE NOT NULL, 
    [ID_OFERTA] INT NOT NULL, 
    CONSTRAINT [FK_Creditos_ToNucleo] FOREIGN KEY ([ID_NUCLEO]) REFERENCES [InfoCredito_Nucleos]([ID_NUCLEO])
)
