CREATE TABLE [dbo].[InfoCredito_Deudas]
(
	[ID_DEUDA] INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
    [ID_CREDITO] INT NOT NULL, 
    [AMC_MONTO] INT NOT NULL , 
    [FECHA_MONTO] INT NOT NULL, 
    [PAGO] BIT NOT NULL DEFAULT 0, 
    [FECHA_VENCIMIENTO] DATE NOT NULL, 
    CONSTRAINT [CK_InfoCredito_Deudas_AMC_MONTO] CHECK (AMC_MONTO BETWEEN 1000000 AND 999999) 
)
