CREATE TABLE [dbo].[InfoCredito_Personas]
(
    [ID_PERSONA] INT NOT NULL IDENTITY (1, 1) PRIMARY KEY,  
    [DOCUMENTO] INT NOT NULL, 
    [PRIMER_NOMBRE] NVARCHAR(MAX) NOT NULL, 
    [SEGUNDO_NOMBRE] NVARCHAR(MAX) NULL, 
    [PRIMER_APELLIDO] NVARCHAR(MAX) NOT NULL, 
    [SEGUNDO_APELLIDO] NVARCHAR(MAX) NULL, 
    [ID_DIRECCION] INT NOT NULL, 
    [FECHA_NACIMIENTO] DATE NOT NULL, 
    [ACTIVO] BIT NOT NULL DEFAULT 1, 
    [FECHA_ACTUALIZACION] DATE NULL, 
    [ID_CONTACTO] INT NOT NULL, 
    CONSTRAINT [FK_Personas_ToDirecciones] FOREIGN KEY ([ID_DIRECCION]) REFERENCES [InfoCredito_Direcciones]([ID_DIRECCION]),
    CONSTRAINT [FK_Personas_ToContactos] FOREIGN KEY ([ID_CONTACTO]) REFERENCES [InfoCredito_Contactos]([ID_CONTACTO])
);
GO

CREATE UNIQUE INDEX UX_InfoCredito_Personas_Documento_Activo
ON dbo.InfoCredito_Personas (DOCUMENTO)
WHERE ACTIVO = 1