CREATE TABLE [dbo].[InfoCredito_Contactos]
(
	[ID_CONTACTO] INT NOT NULL PRIMARY KEY IDENTITY (1, 1), 
    [TEL_MOVIL] NVARCHAR(50) NULL, 
    [TEL_FIJO] NVARCHAR(50) NULL, 
    [CORREO_ELECTRONICO] NVARCHAR(MAX) NULL, 
    [CORREO_ELECTRONICO_ALT] NVARCHAR(MAX) NULL, 
    [WHATSAPP_URL] NVARCHAR(MAX) NULL, 
    [OBSERVACIONES] NVARCHAR(MAX) NULL
)
