CREATE TABLE [dbo].[Personas]
(
	[DOCUMENTO] INT NOT NULL , 
    [PRIMER_NOMBRE] NVARCHAR(MAX) NOT NULL, 
    [SEGUNDO_NOMBRE] NVARCHAR(MAX) NULL, 
    [PRIMER_APELLIDO] NVARCHAR(MAX) NOT NULL, 
    [SEGUNDO_APELLIDO] NVARCHAR(MAX) NULL, 
    [DIRECCION_ID] INT NOT NULL, 
    [FECHA_NACIMIENTO] NCHAR(10) NOT NULL, 
    PRIMARY KEY ([DOCUMENTO]), 
    CONSTRAINT [FK_Personas_ToDirecciones] FOREIGN KEY ([Column]) REFERENCES [ToTable]([ToTableColumn])
)
