name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: WinFormTester.sln
      Test_Project_Path: TestPro\TestPro.csproj 
      Wap_Project_Directory: TesterProyect
      DatabaseProj: TesterDatabase

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install dependencies
      run: dotnet restore

    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build solution excluding SSDT project
      run: dotnet build ${{ env.Solution_Name }} -c ${{ matrix.configuration }} /p:ExcludeProjects=env.DatabaseProj
     
    - name: Execute unit tests
      run: dotnet test
