name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: WinFormTester.sln
      Test_Project_Path: TestPro\TestPro.csproj 
      Wap_Project_Directory: TesterProject
      DatabaseProj: TesterDatabase\TesterDatabase.sqlproj
      WINDOWS_SERVER_IP: ${{ secrets.WINDOWS_SERVER_IP }}
      WINDOWS_SERVER_USERNAME: ${{ secrets.WINDOWS_SERVER_USERNAME }}
      WINDOWS_SERVER_PASSWORD: ${{ secrets.WINDOWS_SERVER_PASSWORD }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Remove SSDT project from solution
      run: dotnet sln ${{ env.Solution_Name }} remove ${{ env.DatabaseProj }}

    - name: Install dependencies
      run: dotnet restore ${{ env.Solution_Name }}
      
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build solution excluding SSDT project
      run: dotnet build ${{ env.Solution_Name }} -c ${{ matrix.configuration }}
  
    - name: Execute unit tests
      run: dotnet test

    - name: Publish TesterProject for deployment
      run: dotnet publish ${{ env.Wap_Project_Directory}} -c ${{ matrix.configuration }} -o ${{ github.workspace }}/publish


    - name: Deploy TesterProject DLLs via SCP using native command
      run: |
        scp -P 22 -o StrictHostKeyChecking=no -r ${{ github.workspace }}/publish/**/*.dll ${{ env.WINDOWS_SERVER_USERNAME }}@${{ env.WINDOWS_SERVER_IP }}:C:/wintest_publish/

    - name: Deploy TesterProject Dependencies (si existen)
      run: |
        if exist ${{ github.workspace }}/publish/*.deps.json (
          uses: appleboy/scp-action@master
          with:
            host: ${{ env.WINDOWS_SERVER_IP }}
            username: ${{ env.WINDOWS_SERVER_USERNAME }}
            password: ${{ env.WINDOWS_SERVER_PASSWORD }}
            port: 22
            source: "${{ github.workspace }}/publish/*.deps.json"
            target: 'C:/wintest_publish'
            strip_components: 1
        )

